services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
